  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
    web:
      build:
        context: .
        dockerfile: Dockerfile.dev
      command: make run
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - db
